spring:
  datasource:
    db1:
      url: jdbc:mysql:///db1?serverTimezone=GMT%2B8
      driver: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    db2:
      url: jdbc:mysql:///db2?serverTimezone=GMT%2B8
      driver: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456




mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
